### ISSUE TITLE
Drop Down Issue

### ISSUE THREAD

**Issue by Sramos9191** [geekwise-jennifer-tablett/geekwise-academy#3]
Page: Cohort
Issue: Drop down not working properly

![screen shot 2016-03-18 at 1 46 17 pm](https://cloud.githubusercontent.com/assets/7436666/13891738/1d44e740-ed10-11e5-9359-2f8da0d983ab.png)
- http://www.sitepoint.com/css3-vertical-accordion-using-target-selector/ 
  try the accordion instead of the drop down menu - I think it'll work better for what you're trying to do
  @geekwise-jennifer-tablett

**Comment by geekwise-jennifer-tablett** [comment]
dropdown works, working on content next
