### ISSUE TITLE
navbar

### ISSUE THREAD

**Issue by haniali1234** [geekwise-jennifer-tablett/geekwise-academy#4]
page: Home
issue:  Geekwise logo shouldnt be there. you have a checkbox. display none on it and you have too much white background height

photo:
## Geekwise Site

**![screen shot 2016-04-05 at 8 48 48 am](https://cloud.githubusercontent.com/assets/11038599/14288496/c92d0d22-fb0b-11e5-8bee-7d860a2a807e.png)
## **Your Site

**![screen shot 2016-04-05 at 8 48 37 am](https://cloud.githubusercontent.com/assets/11038599/14288499/cc16a2aa-fb0b-11e5-9137-194ac640c6ee.png)

**Comment by geekwise-jennifer-tablett** [comment]
done
