### ISSUE TITLE
navbar

### ISSUE THREAD

**Issue by haniali1234** [geekwise-jennifer-tablett/geekwise-academy#5]
page: Courses
issue: no background white and the width is around 80%;
photo:
## geekwise site

![screen shot 2016-04-06 at 9 14 30 am](https://cloud.githubusercontent.com/assets/11038599/14324012/fdcb5058-fbd7-11e5-814c-c527c477b911.png)
## Your Site

![screen shot 2016-04-06 at 9 06 02 am](https://cloud.githubusercontent.com/assets/11038599/14323973/cd66c1e0-fbd7-11e5-9d83-4c21487e934a.png)

**Comment by geekwise-jennifer-tablett** [comment]
done
